name:                hs-web3
version:             0.1.0.0
github:              "githubuser/hs-web3"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-web3#readme>

dependencies:
  - base >=4.7 && <5
  - text                 >1.2  && <1.3
  - bitvec               >1.0  && <2.0
  - vector               >0.12 && <0.13
  - memory               >0.14 && <0.17
  - bytestring           >0.10 && <0.11
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hs-web3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-web3

tests:
  hs-web3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-web3
    - HUnit
    - scale
    - bytestring >0.10    && <0.11
    - hspec-expectations   >=0.8.2  && <0.9
    - hspec-discover       >=2.4.4  && <2.9
    - hspec-contrib        >=0.4.0  && <0.6
    - hspec                >=2.4.4  && <2.9