name: cScale-test

on:
  push:
    branches: [main]
    paths:
      - 'cScale/**'
      - '.github/workflows/cScale.yml'
jobs:
  test:
    name: Build and TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: build-ffi
        run: |
          make

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
          cmake: true
          clangtidy: true

      - name: Test
        run: |
          cd cScale
          cmake . 
          cmake --build .
          ./MyProject
