name: scale-go-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build and TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
      - run: make

      - uses: actions/setup-go@v1
        with:
          go-version: 1.17.10

      - name: Test
        working-directory: scale.go
        run: |
          go test -v ./...
