name: scale-php-test

on:
  push:
    branches: [main]
    paths:
      - 'php-scale-codec/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'php-scale-codec/**'
jobs:
  test:
    name: Build and TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: build-ffi
        run: make

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: gmp
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
        working-directory: php-scale-codec

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          working-directory: php-scale-codec
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist
        working-directory: php-scale-codec

      - name: UnitTest
        run: |
          cd php-scale-codec
          make test