name: scale-python-test

on:
  push:
    branches: [main]
    paths:
      - 'py-scale-codec/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'py-scale-codec/**'
jobs:
  test:
    name: Build and TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: build-ffi
        run: make

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Test
        run: |
          cd py-scale-codec
          pip install -r requirements.txt
          python -m unittest discover
