name: scale-js-test

on:
  push:
    branches: [main]
    paths:
      - 'polkadot-js/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'polkadot-js/**'
jobs:
  test:
    name: Build and TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: build-ffi
        run: make

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          
      - name: Test
        run: |
          cd polkadot-js
          npm install
          npm test
