name: scale-codec-cpp-test

on:
  push:
    branches: [main]
    paths:
      - 'scale-codec-cpp/**'
      - '.github/workflows/scale-codec-cpp.yml'
jobs:
  test:
    name: Build and TEST
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: build-ffi
        run: make

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
          cmake: true
          clangtidy: true

      - name: Test
        run: |
          cd scale-codec-cpp
          cmake .
          cmake --build . --target scaleCodecCpp -j 8
          ./scaleCodecCpp
