name: scale-go-test

on:
  push:
    branches: [main]

jobs:
  test:
    name: Build and TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      
      - uses: actions-rs/cargo@v1
        with:
          command: build
      
      - name: build-ffi
        run: |
           mv target/debug/libscale_ffi.so lib/libscale_ffi.so
           
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17.10

      - name: Test
        run: |
          make testScaleGo
