name: scale-go-test

on:
  push:
    branches: [main]
#    paths:
#      - 'scale.go/**'

jobs:
  test:
    name: Build and TEST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

#      - name: build-ffi
#        run: make

      - uses: actions/setup-go@v1
        with:
          go-version: 1.17.10

      - name: Test
        run: |
          ls -l /home/runner/work/scale-codec-comparator/scale-codec-comparator/lib
          cd scale.go
          go test -v ./...